// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AgentieProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AgentieProto {

  /// <summary>Holder for reflection information generated from AgentieProto.proto</summary>
  public static partial class AgentieProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for AgentieProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AgentieProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJBZ2VudGllUHJvdG8ucHJvdG8iLQoHQW5nYWphdBIQCgh1c2VybmFtZRgB",
            "IAEoCRIQCghwYXNzd29yZBgCIAEoCSKNAQoIRXhjdXJzaWUSDAoEdXVpZBgB",
            "IAEoCRIYChBvYmllY3RpdlR1cmlzdGljGAIgASgJEhoKEm51bWVGaXJtYVRy",
            "YW5zcG9ydBgDIAEoCRISCgpvcmFQbGVjYXJlGAQgASgJEhsKE25yTG9jdXJp",
            "RGlzcG9uaWJpbGUYBSABKAUSDAoEcHJldBgGIAEoASJPCg9FeGN1cnNpZVJl",
            "cXVlc3QSGAoQb2JpZWN0aXZUdXJpc3RpYxgBIAEoCRIPCgdkZUxhT3JhGAYg",
            "ASgFEhEKCXBhbmFMYU9yYRgHIAEoBSJ4CglSZXplcnZhcmUSDAoEdXVpZBgB",
            "IAEoCRISCgpudW1lQ2xpZW50GAIgASgJEhoKEm51bWFyVGVsZWZvbkNsaWVu",
            "dBgDIAEoCRIQCghuckJpbGV0ZRgEIAEoBRIbCghleGN1cnNpZRgFIAEoCzIJ",
            "LkV4Y3Vyc2llIvUCCg5BZ2VudGllUmVxdWVzdBIiCgR0eXBlGAEgASgOMhQu",
            "QWdlbnRpZVJlcXVlc3QuVHlwZRIbCgdhbmdhamF0GAIgASgLMgguQW5nYWph",
            "dEgAEh0KCGV4Y3Vyc2llGAMgASgLMgkuRXhjdXJzaWVIABIfCglyZXplcnZh",
            "cmUYBCABKAsyCi5SZXplcnZhcmVIABIrCg9leGN1cnNpZVJlcXVlc3QYBSAB",
            "KAsyEC5FeGN1cnNpZVJlcXVlc3RIACKpAQoEVHlwZRILCgdVbmtub3duEAAS",
            "CQoFTG9naW4QARIKCgZMb2dvdXQQAhIRCg1DYXV0YUV4Y3Vyc2lpEAMSGAoU",
            "Q2F1dGFUb2F0ZUV4Y3Vyc2lpbGUQBBIdChlVcGRhdGVOdW1hckxvY3VyaUV4",
            "Y3Vyc2llEAUSEwoPQWRhdWdhUmV6ZXJ2YXJlEAYSHAoYQ2F1dGFBbmdhamF0",
            "RHVwYVVzZXJuYW1lEAdCCQoHcGF5bG9hZCKNAwoPQWdlbnRpZVJlc3BvbnNl",
            "EiMKBHR5cGUYASABKA4yFS5BZ2VudGllUmVzcG9uc2UuVHlwZRINCgVlcnJv",
            "chgCIAEoCRIZCgdhbmdhamF0GAMgASgLMgguQW5nYWphdBIiCg91cGRhdGVk",
            "RXhjdXJzaWUYBCABKAsyCS5FeGN1cnNpZRIiCg9leGN1cnNpaUNhdXRhdGUY",
            "BSADKAsyCS5FeGN1cnNpZRIiCg90b2F0ZUV4Y3Vyc2lpbGUYBiADKAsyCS5F",
            "eGN1cnNpZRIdCglyZXplcnZhcmUYByABKAsyCi5SZXplcnZhcmUinwEKBFR5",
            "cGUSCwoHVW5rbm93bhAAEgYKAk9rEAESCQoFRXJyb3IQAhITCg9FeGN1cnNp",
            "aUNhdXRhdGUQAxITCg9Ub2F0ZUV4Y3Vyc2lpbGUQBBIeChpVcGRhdGVkTnVt",
            "YXJMb2N1cmlFeGN1cnNpZRAFEhUKEVJlemVydmFyZUFkYXVnYXRhEAYSFgoS",
            "RXhjdXJzaWVNb2RpZmljYXRhEAdCD6oCDEFnZW50aWVQcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AgentieProto.Angajat), global::AgentieProto.Angajat.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AgentieProto.Excursie), global::AgentieProto.Excursie.Parser, new[]{ "Uuid", "ObiectivTuristic", "NumeFirmaTransport", "OraPlecare", "NrLocuriDisponibile", "Pret" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AgentieProto.ExcursieRequest), global::AgentieProto.ExcursieRequest.Parser, new[]{ "ObiectivTuristic", "DeLaOra", "PanaLaOra" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AgentieProto.Rezervare), global::AgentieProto.Rezervare.Parser, new[]{ "Uuid", "NumeClient", "NumarTelefonClient", "NrBilete", "Excursie" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AgentieProto.AgentieRequest), global::AgentieProto.AgentieRequest.Parser, new[]{ "Type", "Angajat", "Excursie", "Rezervare", "ExcursieRequest" }, new[]{ "Payload" }, new[]{ typeof(global::AgentieProto.AgentieRequest.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AgentieProto.AgentieResponse), global::AgentieProto.AgentieResponse.Parser, new[]{ "Type", "Error", "Angajat", "UpdatedExcursie", "ExcursiiCautate", "ToateExcursiile", "Rezervare" }, null, new[]{ typeof(global::AgentieProto.AgentieResponse.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Angajat : pb::IMessage<Angajat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgentieProto.AgentieProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat(Angajat other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat Clone() {
      return new Angajat(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Angajat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Angajat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Angajat other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Excursie : pb::IMessage<Excursie>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Excursie> _parser = new pb::MessageParser<Excursie>(() => new Excursie());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Excursie> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgentieProto.AgentieProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie(Excursie other) : this() {
      uuid_ = other.uuid_;
      obiectivTuristic_ = other.obiectivTuristic_;
      numeFirmaTransport_ = other.numeFirmaTransport_;
      oraPlecare_ = other.oraPlecare_;
      nrLocuriDisponibile_ = other.nrLocuriDisponibile_;
      pret_ = other.pret_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Excursie Clone() {
      return new Excursie(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private string uuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "obiectivTuristic" field.</summary>
    public const int ObiectivTuristicFieldNumber = 2;
    private string obiectivTuristic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObiectivTuristic {
      get { return obiectivTuristic_; }
      set {
        obiectivTuristic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeFirmaTransport" field.</summary>
    public const int NumeFirmaTransportFieldNumber = 3;
    private string numeFirmaTransport_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeFirmaTransport {
      get { return numeFirmaTransport_; }
      set {
        numeFirmaTransport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oraPlecare" field.</summary>
    public const int OraPlecareFieldNumber = 4;
    private string oraPlecare_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OraPlecare {
      get { return oraPlecare_; }
      set {
        oraPlecare_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuriDisponibile" field.</summary>
    public const int NrLocuriDisponibileFieldNumber = 5;
    private int nrLocuriDisponibile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuriDisponibile {
      get { return nrLocuriDisponibile_; }
      set {
        nrLocuriDisponibile_ = value;
      }
    }

    /// <summary>Field number for the "pret" field.</summary>
    public const int PretFieldNumber = 6;
    private double pret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Pret {
      get { return pret_; }
      set {
        pret_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Excursie);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Excursie other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uuid != other.Uuid) return false;
      if (ObiectivTuristic != other.ObiectivTuristic) return false;
      if (NumeFirmaTransport != other.NumeFirmaTransport) return false;
      if (OraPlecare != other.OraPlecare) return false;
      if (NrLocuriDisponibile != other.NrLocuriDisponibile) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Pret, other.Pret)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (ObiectivTuristic.Length != 0) hash ^= ObiectivTuristic.GetHashCode();
      if (NumeFirmaTransport.Length != 0) hash ^= NumeFirmaTransport.GetHashCode();
      if (OraPlecare.Length != 0) hash ^= OraPlecare.GetHashCode();
      if (NrLocuriDisponibile != 0) hash ^= NrLocuriDisponibile.GetHashCode();
      if (Pret != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Pret);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uuid);
      }
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObiectivTuristic);
      }
      if (NumeFirmaTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeFirmaTransport);
      }
      if (OraPlecare.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OraPlecare);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (Pret != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Pret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uuid);
      }
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObiectivTuristic);
      }
      if (NumeFirmaTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumeFirmaTransport);
      }
      if (OraPlecare.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OraPlecare);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (Pret != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Pret);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (ObiectivTuristic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObiectivTuristic);
      }
      if (NumeFirmaTransport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeFirmaTransport);
      }
      if (OraPlecare.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OraPlecare);
      }
      if (NrLocuriDisponibile != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuriDisponibile);
      }
      if (Pret != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Excursie other) {
      if (other == null) {
        return;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      if (other.ObiectivTuristic.Length != 0) {
        ObiectivTuristic = other.ObiectivTuristic;
      }
      if (other.NumeFirmaTransport.Length != 0) {
        NumeFirmaTransport = other.NumeFirmaTransport;
      }
      if (other.OraPlecare.Length != 0) {
        OraPlecare = other.OraPlecare;
      }
      if (other.NrLocuriDisponibile != 0) {
        NrLocuriDisponibile = other.NrLocuriDisponibile;
      }
      if (other.Pret != 0D) {
        Pret = other.Pret;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uuid = input.ReadString();
            break;
          }
          case 18: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 26: {
            NumeFirmaTransport = input.ReadString();
            break;
          }
          case 34: {
            OraPlecare = input.ReadString();
            break;
          }
          case 40: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
          case 49: {
            Pret = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uuid = input.ReadString();
            break;
          }
          case 18: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 26: {
            NumeFirmaTransport = input.ReadString();
            break;
          }
          case 34: {
            OraPlecare = input.ReadString();
            break;
          }
          case 40: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
          case 49: {
            Pret = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExcursieRequest : pb::IMessage<ExcursieRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExcursieRequest> _parser = new pb::MessageParser<ExcursieRequest>(() => new ExcursieRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExcursieRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgentieProto.AgentieProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExcursieRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExcursieRequest(ExcursieRequest other) : this() {
      obiectivTuristic_ = other.obiectivTuristic_;
      deLaOra_ = other.deLaOra_;
      panaLaOra_ = other.panaLaOra_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExcursieRequest Clone() {
      return new ExcursieRequest(this);
    }

    /// <summary>Field number for the "obiectivTuristic" field.</summary>
    public const int ObiectivTuristicFieldNumber = 1;
    private string obiectivTuristic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObiectivTuristic {
      get { return obiectivTuristic_; }
      set {
        obiectivTuristic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deLaOra" field.</summary>
    public const int DeLaOraFieldNumber = 6;
    private int deLaOra_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeLaOra {
      get { return deLaOra_; }
      set {
        deLaOra_ = value;
      }
    }

    /// <summary>Field number for the "panaLaOra" field.</summary>
    public const int PanaLaOraFieldNumber = 7;
    private int panaLaOra_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PanaLaOra {
      get { return panaLaOra_; }
      set {
        panaLaOra_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExcursieRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExcursieRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ObiectivTuristic != other.ObiectivTuristic) return false;
      if (DeLaOra != other.DeLaOra) return false;
      if (PanaLaOra != other.PanaLaOra) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ObiectivTuristic.Length != 0) hash ^= ObiectivTuristic.GetHashCode();
      if (DeLaOra != 0) hash ^= DeLaOra.GetHashCode();
      if (PanaLaOra != 0) hash ^= PanaLaOra.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObiectivTuristic);
      }
      if (DeLaOra != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DeLaOra);
      }
      if (PanaLaOra != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(PanaLaOra);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObiectivTuristic);
      }
      if (DeLaOra != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DeLaOra);
      }
      if (PanaLaOra != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(PanaLaOra);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ObiectivTuristic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObiectivTuristic);
      }
      if (DeLaOra != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeLaOra);
      }
      if (PanaLaOra != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PanaLaOra);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExcursieRequest other) {
      if (other == null) {
        return;
      }
      if (other.ObiectivTuristic.Length != 0) {
        ObiectivTuristic = other.ObiectivTuristic;
      }
      if (other.DeLaOra != 0) {
        DeLaOra = other.DeLaOra;
      }
      if (other.PanaLaOra != 0) {
        PanaLaOra = other.PanaLaOra;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 48: {
            DeLaOra = input.ReadInt32();
            break;
          }
          case 56: {
            PanaLaOra = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 48: {
            DeLaOra = input.ReadInt32();
            break;
          }
          case 56: {
            PanaLaOra = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Rezervare : pb::IMessage<Rezervare>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Rezervare> _parser = new pb::MessageParser<Rezervare>(() => new Rezervare());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Rezervare> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgentieProto.AgentieProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezervare() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezervare(Rezervare other) : this() {
      uuid_ = other.uuid_;
      numeClient_ = other.numeClient_;
      numarTelefonClient_ = other.numarTelefonClient_;
      nrBilete_ = other.nrBilete_;
      excursie_ = other.excursie_ != null ? other.excursie_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Rezervare Clone() {
      return new Rezervare(this);
    }

    /// <summary>Field number for the "uuid" field.</summary>
    public const int UuidFieldNumber = 1;
    private string uuid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uuid {
      get { return uuid_; }
      set {
        uuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 2;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numarTelefonClient" field.</summary>
    public const int NumarTelefonClientFieldNumber = 3;
    private string numarTelefonClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumarTelefonClient {
      get { return numarTelefonClient_; }
      set {
        numarTelefonClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrBilete" field.</summary>
    public const int NrBileteFieldNumber = 4;
    private int nrBilete_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrBilete {
      get { return nrBilete_; }
      set {
        nrBilete_ = value;
      }
    }

    /// <summary>Field number for the "excursie" field.</summary>
    public const int ExcursieFieldNumber = 5;
    private global::AgentieProto.Excursie excursie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Excursie Excursie {
      get { return excursie_; }
      set {
        excursie_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Rezervare);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Rezervare other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uuid != other.Uuid) return false;
      if (NumeClient != other.NumeClient) return false;
      if (NumarTelefonClient != other.NumarTelefonClient) return false;
      if (NrBilete != other.NrBilete) return false;
      if (!object.Equals(Excursie, other.Excursie)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uuid.Length != 0) hash ^= Uuid.GetHashCode();
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (NumarTelefonClient.Length != 0) hash ^= NumarTelefonClient.GetHashCode();
      if (NrBilete != 0) hash ^= NrBilete.GetHashCode();
      if (excursie_ != null) hash ^= Excursie.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uuid);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NumarTelefonClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumarTelefonClient);
      }
      if (NrBilete != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NrBilete);
      }
      if (excursie_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Excursie);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uuid);
      }
      if (NumeClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeClient);
      }
      if (NumarTelefonClient.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NumarTelefonClient);
      }
      if (NrBilete != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NrBilete);
      }
      if (excursie_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Excursie);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uuid);
      }
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (NumarTelefonClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumarTelefonClient);
      }
      if (NrBilete != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrBilete);
      }
      if (excursie_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Excursie);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Rezervare other) {
      if (other == null) {
        return;
      }
      if (other.Uuid.Length != 0) {
        Uuid = other.Uuid;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.NumarTelefonClient.Length != 0) {
        NumarTelefonClient = other.NumarTelefonClient;
      }
      if (other.NrBilete != 0) {
        NrBilete = other.NrBilete;
      }
      if (other.excursie_ != null) {
        if (excursie_ == null) {
          Excursie = new global::AgentieProto.Excursie();
        }
        Excursie.MergeFrom(other.Excursie);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Uuid = input.ReadString();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 26: {
            NumarTelefonClient = input.ReadString();
            break;
          }
          case 32: {
            NrBilete = input.ReadInt32();
            break;
          }
          case 42: {
            if (excursie_ == null) {
              Excursie = new global::AgentieProto.Excursie();
            }
            input.ReadMessage(Excursie);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Uuid = input.ReadString();
            break;
          }
          case 18: {
            NumeClient = input.ReadString();
            break;
          }
          case 26: {
            NumarTelefonClient = input.ReadString();
            break;
          }
          case 32: {
            NrBilete = input.ReadInt32();
            break;
          }
          case 42: {
            if (excursie_ == null) {
              Excursie = new global::AgentieProto.Excursie();
            }
            input.ReadMessage(Excursie);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgentieRequest : pb::IMessage<AgentieRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgentieRequest> _parser = new pb::MessageParser<AgentieRequest>(() => new AgentieRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgentieRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgentieProto.AgentieProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentieRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentieRequest(AgentieRequest other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Angajat:
          Angajat = other.Angajat.Clone();
          break;
        case PayloadOneofCase.Excursie:
          Excursie = other.Excursie.Clone();
          break;
        case PayloadOneofCase.Rezervare:
          Rezervare = other.Rezervare.Clone();
          break;
        case PayloadOneofCase.ExcursieRequest:
          ExcursieRequest = other.ExcursieRequest.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentieRequest Clone() {
      return new AgentieRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::AgentieProto.AgentieRequest.Types.Type type_ = global::AgentieProto.AgentieRequest.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.AgentieRequest.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Angajat Angajat {
      get { return payloadCase_ == PayloadOneofCase.Angajat ? (global::AgentieProto.Angajat) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Angajat;
      }
    }

    /// <summary>Field number for the "excursie" field.</summary>
    public const int ExcursieFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Excursie Excursie {
      get { return payloadCase_ == PayloadOneofCase.Excursie ? (global::AgentieProto.Excursie) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Excursie;
      }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Rezervare Rezervare {
      get { return payloadCase_ == PayloadOneofCase.Rezervare ? (global::AgentieProto.Rezervare) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Rezervare;
      }
    }

    /// <summary>Field number for the "excursieRequest" field.</summary>
    public const int ExcursieRequestFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.ExcursieRequest ExcursieRequest {
      get { return payloadCase_ == PayloadOneofCase.ExcursieRequest ? (global::AgentieProto.ExcursieRequest) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ExcursieRequest;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Angajat = 2,
      Excursie = 3,
      Rezervare = 4,
      ExcursieRequest = 5,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgentieRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgentieRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (!object.Equals(Excursie, other.Excursie)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      if (!object.Equals(ExcursieRequest, other.ExcursieRequest)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::AgentieProto.AgentieRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Angajat) hash ^= Angajat.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Excursie) hash ^= Excursie.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Rezervare) hash ^= Rezervare.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ExcursieRequest) hash ^= ExcursieRequest.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::AgentieProto.AgentieRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (payloadCase_ == PayloadOneofCase.Excursie) {
        output.WriteRawTag(26);
        output.WriteMessage(Excursie);
      }
      if (payloadCase_ == PayloadOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      if (payloadCase_ == PayloadOneofCase.ExcursieRequest) {
        output.WriteRawTag(42);
        output.WriteMessage(ExcursieRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::AgentieProto.AgentieRequest.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (payloadCase_ == PayloadOneofCase.Excursie) {
        output.WriteRawTag(26);
        output.WriteMessage(Excursie);
      }
      if (payloadCase_ == PayloadOneofCase.Rezervare) {
        output.WriteRawTag(34);
        output.WriteMessage(Rezervare);
      }
      if (payloadCase_ == PayloadOneofCase.ExcursieRequest) {
        output.WriteRawTag(42);
        output.WriteMessage(ExcursieRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::AgentieProto.AgentieRequest.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (payloadCase_ == PayloadOneofCase.Excursie) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Excursie);
      }
      if (payloadCase_ == PayloadOneofCase.Rezervare) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      if (payloadCase_ == PayloadOneofCase.ExcursieRequest) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExcursieRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgentieRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::AgentieProto.AgentieRequest.Types.Type.Unknown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Angajat:
          if (Angajat == null) {
            Angajat = new global::AgentieProto.Angajat();
          }
          Angajat.MergeFrom(other.Angajat);
          break;
        case PayloadOneofCase.Excursie:
          if (Excursie == null) {
            Excursie = new global::AgentieProto.Excursie();
          }
          Excursie.MergeFrom(other.Excursie);
          break;
        case PayloadOneofCase.Rezervare:
          if (Rezervare == null) {
            Rezervare = new global::AgentieProto.Rezervare();
          }
          Rezervare.MergeFrom(other.Rezervare);
          break;
        case PayloadOneofCase.ExcursieRequest:
          if (ExcursieRequest == null) {
            ExcursieRequest = new global::AgentieProto.ExcursieRequest();
          }
          ExcursieRequest.MergeFrom(other.ExcursieRequest);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::AgentieProto.AgentieRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::AgentieProto.Angajat subBuilder = new global::AgentieProto.Angajat();
            if (payloadCase_ == PayloadOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 26: {
            global::AgentieProto.Excursie subBuilder = new global::AgentieProto.Excursie();
            if (payloadCase_ == PayloadOneofCase.Excursie) {
              subBuilder.MergeFrom(Excursie);
            }
            input.ReadMessage(subBuilder);
            Excursie = subBuilder;
            break;
          }
          case 34: {
            global::AgentieProto.Rezervare subBuilder = new global::AgentieProto.Rezervare();
            if (payloadCase_ == PayloadOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
          case 42: {
            global::AgentieProto.ExcursieRequest subBuilder = new global::AgentieProto.ExcursieRequest();
            if (payloadCase_ == PayloadOneofCase.ExcursieRequest) {
              subBuilder.MergeFrom(ExcursieRequest);
            }
            input.ReadMessage(subBuilder);
            ExcursieRequest = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::AgentieProto.AgentieRequest.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::AgentieProto.Angajat subBuilder = new global::AgentieProto.Angajat();
            if (payloadCase_ == PayloadOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 26: {
            global::AgentieProto.Excursie subBuilder = new global::AgentieProto.Excursie();
            if (payloadCase_ == PayloadOneofCase.Excursie) {
              subBuilder.MergeFrom(Excursie);
            }
            input.ReadMessage(subBuilder);
            Excursie = subBuilder;
            break;
          }
          case 34: {
            global::AgentieProto.Rezervare subBuilder = new global::AgentieProto.Rezervare();
            if (payloadCase_ == PayloadOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
          case 42: {
            global::AgentieProto.ExcursieRequest subBuilder = new global::AgentieProto.ExcursieRequest();
            if (payloadCase_ == PayloadOneofCase.ExcursieRequest) {
              subBuilder.MergeFrom(ExcursieRequest);
            }
            input.ReadMessage(subBuilder);
            ExcursieRequest = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AgentieRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("CautaExcursii")] CautaExcursii = 3,
        [pbr::OriginalName("CautaToateExcursiile")] CautaToateExcursiile = 4,
        [pbr::OriginalName("UpdateNumarLocuriExcursie")] UpdateNumarLocuriExcursie = 5,
        [pbr::OriginalName("AdaugaRezervare")] AdaugaRezervare = 6,
        [pbr::OriginalName("CautaAngajatDupaUsername")] CautaAngajatDupaUsername = 7,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AgentieResponse : pb::IMessage<AgentieResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AgentieResponse> _parser = new pb::MessageParser<AgentieResponse>(() => new AgentieResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AgentieResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AgentieProto.AgentieProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentieResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentieResponse(AgentieResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
      updatedExcursie_ = other.updatedExcursie_ != null ? other.updatedExcursie_.Clone() : null;
      excursiiCautate_ = other.excursiiCautate_.Clone();
      toateExcursiile_ = other.toateExcursiile_.Clone();
      rezervare_ = other.rezervare_ != null ? other.rezervare_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AgentieResponse Clone() {
      return new AgentieResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::AgentieProto.AgentieResponse.Types.Type type_ = global::AgentieProto.AgentieResponse.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.AgentieResponse.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 3;
    private global::AgentieProto.Angajat angajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Angajat Angajat {
      get { return angajat_; }
      set {
        angajat_ = value;
      }
    }

    /// <summary>Field number for the "updatedExcursie" field.</summary>
    public const int UpdatedExcursieFieldNumber = 4;
    private global::AgentieProto.Excursie updatedExcursie_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Excursie UpdatedExcursie {
      get { return updatedExcursie_; }
      set {
        updatedExcursie_ = value;
      }
    }

    /// <summary>Field number for the "excursiiCautate" field.</summary>
    public const int ExcursiiCautateFieldNumber = 5;
    private static readonly pb::FieldCodec<global::AgentieProto.Excursie> _repeated_excursiiCautate_codec
        = pb::FieldCodec.ForMessage(42, global::AgentieProto.Excursie.Parser);
    private readonly pbc::RepeatedField<global::AgentieProto.Excursie> excursiiCautate_ = new pbc::RepeatedField<global::AgentieProto.Excursie>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AgentieProto.Excursie> ExcursiiCautate {
      get { return excursiiCautate_; }
    }

    /// <summary>Field number for the "toateExcursiile" field.</summary>
    public const int ToateExcursiileFieldNumber = 6;
    private static readonly pb::FieldCodec<global::AgentieProto.Excursie> _repeated_toateExcursiile_codec
        = pb::FieldCodec.ForMessage(50, global::AgentieProto.Excursie.Parser);
    private readonly pbc::RepeatedField<global::AgentieProto.Excursie> toateExcursiile_ = new pbc::RepeatedField<global::AgentieProto.Excursie>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AgentieProto.Excursie> ToateExcursiile {
      get { return toateExcursiile_; }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 7;
    private global::AgentieProto.Rezervare rezervare_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AgentieProto.Rezervare Rezervare {
      get { return rezervare_; }
      set {
        rezervare_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AgentieResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AgentieResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (!object.Equals(UpdatedExcursie, other.UpdatedExcursie)) return false;
      if(!excursiiCautate_.Equals(other.excursiiCautate_)) return false;
      if(!toateExcursiile_.Equals(other.toateExcursiile_)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::AgentieProto.AgentieResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (angajat_ != null) hash ^= Angajat.GetHashCode();
      if (updatedExcursie_ != null) hash ^= UpdatedExcursie.GetHashCode();
      hash ^= excursiiCautate_.GetHashCode();
      hash ^= toateExcursiile_.GetHashCode();
      if (rezervare_ != null) hash ^= Rezervare.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::AgentieProto.AgentieResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (angajat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Angajat);
      }
      if (updatedExcursie_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdatedExcursie);
      }
      excursiiCautate_.WriteTo(output, _repeated_excursiiCautate_codec);
      toateExcursiile_.WriteTo(output, _repeated_toateExcursiile_codec);
      if (rezervare_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Rezervare);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::AgentieProto.AgentieResponse.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (angajat_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Angajat);
      }
      if (updatedExcursie_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(UpdatedExcursie);
      }
      excursiiCautate_.WriteTo(ref output, _repeated_excursiiCautate_codec);
      toateExcursiile_.WriteTo(ref output, _repeated_toateExcursiile_codec);
      if (rezervare_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Rezervare);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::AgentieProto.AgentieResponse.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (angajat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (updatedExcursie_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedExcursie);
      }
      size += excursiiCautate_.CalculateSize(_repeated_excursiiCautate_codec);
      size += toateExcursiile_.CalculateSize(_repeated_toateExcursiile_codec);
      if (rezervare_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AgentieResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::AgentieProto.AgentieResponse.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.angajat_ != null) {
        if (angajat_ == null) {
          Angajat = new global::AgentieProto.Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
      }
      if (other.updatedExcursie_ != null) {
        if (updatedExcursie_ == null) {
          UpdatedExcursie = new global::AgentieProto.Excursie();
        }
        UpdatedExcursie.MergeFrom(other.UpdatedExcursie);
      }
      excursiiCautate_.Add(other.excursiiCautate_);
      toateExcursiile_.Add(other.toateExcursiile_);
      if (other.rezervare_ != null) {
        if (rezervare_ == null) {
          Rezervare = new global::AgentieProto.Rezervare();
        }
        Rezervare.MergeFrom(other.Rezervare);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::AgentieProto.AgentieResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (angajat_ == null) {
              Angajat = new global::AgentieProto.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 34: {
            if (updatedExcursie_ == null) {
              UpdatedExcursie = new global::AgentieProto.Excursie();
            }
            input.ReadMessage(UpdatedExcursie);
            break;
          }
          case 42: {
            excursiiCautate_.AddEntriesFrom(input, _repeated_excursiiCautate_codec);
            break;
          }
          case 50: {
            toateExcursiile_.AddEntriesFrom(input, _repeated_toateExcursiile_codec);
            break;
          }
          case 58: {
            if (rezervare_ == null) {
              Rezervare = new global::AgentieProto.Rezervare();
            }
            input.ReadMessage(Rezervare);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::AgentieProto.AgentieResponse.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (angajat_ == null) {
              Angajat = new global::AgentieProto.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 34: {
            if (updatedExcursie_ == null) {
              UpdatedExcursie = new global::AgentieProto.Excursie();
            }
            input.ReadMessage(UpdatedExcursie);
            break;
          }
          case 42: {
            excursiiCautate_.AddEntriesFrom(ref input, _repeated_excursiiCautate_codec);
            break;
          }
          case 50: {
            toateExcursiile_.AddEntriesFrom(ref input, _repeated_toateExcursiile_codec);
            break;
          }
          case 58: {
            if (rezervare_ == null) {
              Rezervare = new global::AgentieProto.Rezervare();
            }
            input.ReadMessage(Rezervare);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AgentieResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("ExcursiiCautate")] ExcursiiCautate = 3,
        [pbr::OriginalName("ToateExcursiile")] ToateExcursiile = 4,
        [pbr::OriginalName("UpdatedNumarLocuriExcursie")] UpdatedNumarLocuriExcursie = 5,
        [pbr::OriginalName("RezervareAdaugata")] RezervareAdaugata = 6,
        [pbr::OriginalName("ExcursieModificata")] ExcursieModificata = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
